### ISSUE TITLE
I see the following error

### ISSUE THREAD

**Issue by pymblesoftware** [pascalgp/elp2pdf#1]
./elp2pdf.pl -
Aug  8 17:18:15 printer started
Hello
Aug  8 17:18:20 reading
Aug  8 17:18:20 processing 1 lines
Aug  8 17:18:20 file PRINTER_2020-08-08-17.18.20.pdf
enscript: do not know anything about media "USFanfold"
Aug  8 17:18:20 done

**Comment by pascalgp** [comment]
A hidden file named .enscriptrc with the USFanfold media definition must be added to the home directory of the user running the script. This file should contain these lines, making sure to replace /home/username with the actual home directory:

`LibraryPath: /home/username/.enscript:/usr/share/enscript`
`Media: USFanfold 999 792 24 24 975 768`

**Comment by pymblesoftware** [comment]
No error but no background either, just the text on white background.

**Comment by pascalgp** [comment]
The background is composed by the modified enscript prolog. There should be a hidden directory named .enscript in the home directory of the user running elp2pdf. For enscript to use the modified prolog:

-  It must be copied from this repository to the .enscript directory
- The path to the .enscript directory should be set correctly for LibraryPath in ~/.enscriptrc

**Comment by pymblesoftware** [comment]
Ok the path was not /usr/share but something else...
But now...

./elp2pdf.pl elp2pdf.pl 
Aug 10 10:35:50 printer started
Aug 10 10:35:50 reading
Aug 10 10:35:50 processing 268 lines
Aug 10 10:35:50 file PRINTER_2020-08-10-10.35.50.pdf
enscript: couldn't find encoding file "88591.enc": Not a directory

Aug 10 10:35:51 done

**Comment by pascalgp** [comment]
The 88591.enc file is installed with enscript and should be in the LibraryPath specified in .enscriptrc
Please try copying the standard 88591.enc file that I just added to the repository to the .enscript directory in your home path.
